#!/bin/sh

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nohup vim +PlugUpdate +PlugClean! -cq >/dev/null 2>&1 </dev/null &
